version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn clean package
    - mvn install
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Hello
# artifacts:
#   files:
#   - target/bike-service-0.0.1-SNAPSHOT.war
#   - scripts/*
