name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Upload build artifacts       
        uses: actions/upload-artifact@v2      
        with:        
           name: War file       
           path: target/HelloWorld.war
           
      - name: Check1
        run: ls target

      - name: create container
        run: docker build . --file Dockerfile -t whs:HelloWorld
        
      - name: Check2
        run: ls
        
      - name: start insecure bank 
        run: |
          docker run -d -p 3005:80 whs:insecure-bank
          wget --quiet --wait=3 http://localhost:3005/install.php?install=yes
